language: node_js
node_js:
  - "8"

dist: trusty
servies:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
   - node_modules
   - client/node_modules
install:
  - yarn install
  - yarn run build
script:
  - nohup yarn run start &
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - yarn run test